config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :favorites do
    member { post :vote }
  end

  get 'home/index', as: "home"

  get '/search' => "search#index", as: "search"

  resources :messages

  get "/backup" => 'messages#import_from_backup'
  post "/backup" => 'messages#import_from_backup_post', as: "import_messages"

  get "/facebook" => 'messages#import_from_facebook'

  root 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base

  has_many :favorites

  require "open-uri"
  require "csv"

  # defualt sort scope
  default_scope { order('created_at ASC') }

  ##############################
  #
  #          SMS & iMessage
  #
  ##############################

  # import from iPhone backup
  def self.import_from_backup(path)
    CSV.foreach(Rails.root + path, headers: true) do |row|
      r = row.to_hash
      r = r.merge({"origin" => "messages"})

      save_phone_message(r)
    end
  end

  def self.save_phone_message(message)
    # data
    data = {}

    data[:foreign_id] = "1"

    data[:sender_contact] = message["Name"].strip
    data[:sender_name] = get_sender(message["Name"].strip)[1]

    data[:receiver_contact] = message["Phone Number"]
    data[:receiver_name] = get_receiver(message["Name"].strip, "messages")[1]

    data[:body] = message["Message"].strip
    data[:origin] = message["origin"]
    data[:message_type] = message["origin"]
    data[:created_at] = DateTime.parse "#{message['Date']} #{Time.zone}"

    # Message.where(body: data[:body], sender_contact: data[:sender_contact], created_at: data[:created_at])

    new_message = Message.create_with(data).find_or_create_by!(body: data[:body], sender_contact: data[:sender_contact], created_at: data[:created_at])

    return new_message
  end

  ##############################
  #
  #          FACEBOOK
  #
  ##############################

  # desc: import facebook messages
  def self.import_from_facebook
    token = "CAACEdEose0cBAPZBJgOOtFAKfXyQvIFz8zTJXK1lE2VomIPWaAqLp0GVY7HCENI9FnZB8oHGFmfLrmYMne93SB3ktjb8fdYpPGzq5CHTrPAWp37JOu2KBJ0Hi2r3seujS1ZAtSpjCUdbSbw1Rv4ZAsxZBI5G126jweux2tsLPi3IUECnvS5ao831MOZAHW6w055Le3SXrmBzgZCy1sYNN86jAl2vIKj9FwZD";
    url = "https://graph.facebook.com/v2.2/555657294533057?access_token=#{token}"

    # parse_facebook_data(url)

    # parse data
    data = URI.parse(url).read
    data = JSON.parse data

    save_messages(data["comments"]["data"])
    start_paging(data["comments"]["paging"]["next"])

  end

  # parse data
  def self.parse_facebook_data(url)
    # parse data
    data = URI.parse(url).read
    data = JSON.parse data

    if data.length > 1
      save_messages(data["data"])
      start_paging(data["paging"]["next"])
    else
      return
    end
  end

  # paging
  def self.start_paging(url)
    parse_facebook_data(url)
  end

  # save message
  def self.save_messages(messages)
    for message in messages do
      self.save_message(message)
    end
  end

  def self.save_message(message)
    # data
    data = {}

    data[:foreign_id] = message["id"]
    data[:sender_contact] = message["from"]["id"].to_s
    data[:sender_name] = message["from"]["name"].to_s
    data[:receiver_contact] = get_receiver(message["from"]["id"].to_i, "facebook")[0]
    data[:receiver_name] = get_receiver(message["from"]["id"].to_i, "facebook")[1]
    data[:body] = message["message"]
    data[:origin] = "facebook"
    data[:message_type] = "facebook"
    data[:created_at] = message["created_time"]

    new_message = Message.create_with(data).find_or_create_by!(foreign_id: message["id"], created_at: message["created_time"])

    return new_message
  end

  # get receiver
  def self.get_receiver(sender, origin)
    id_andre = [100001426361532, "Me"]
    id_linda = [613348845421106, "Linda Voigt", "Babe"]

    name_andre = "Andre Zimpel"
    if origin == "facebook"
      name_linda = "Fräulein Linda"
    else
      name_linda = "Linda Voigt"
    end

    if origin == "facebook"
      if id_andre.include?(sender)
        return [id_linda[0], name_linda]
      elsif id_linda.include?(sender)
        return [id_andre[0], name_andre]
      end
    else
      if id_andre.include?(sender)
        return [id_linda[1], name_linda]
      elsif id_linda.include?(sender)
        return [id_andre[1], name_andre]
      end
    end
  end

  # get sender
  def self.get_sender(sender)
    id_andre = [100001426361532, "Me"]
    id_linda = [613348845421106, "Linda Voigt", "Babe"]

    name_andre = "Andre Zimpel"
    name_linda = "Linda Voigt"

    if id_andre.include?(sender)
      return [id_andre[1], name_andre]
    elsif id_linda.include?(sender)
      return [id_linda[1], name_linda]
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @page_count = params[:page]
    @messages = Message.all.page(@page_count).per(50)
    @message_months = @messages.group_by { |t| t.created_at.beginning_of_day }

    # @messages.group_by_day(:created_at).count
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @favorite = @message.favorites.where(user_id: current_user.id).first

    unless @favorite
      @favorite = Favorite.new
    end

    # save pagination url
    page = request.referer.split("?")[1]

    if page != nil
      @message.update(page_url: page)
    end
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  # custom
  def import_from_backup
  end
  def import_from_backup_post
    path = params[:file].path
    Message.delay.import_from_backup(path)
    redirect_to root_path, notice: "Importing Messages."
  end

  def import_from_facebook
    Message.delay.import_from_facebook
    redirect_to root_path, notice: "Importing Messages."
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:sender_contact, :sender_name, :receiver_contact, :receiver_name, :body, :origin, :message_type, :foreign_id, :page_url)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
  # date & time
  def message_date(message)
    return get_date(message.created_at)
  end
  def get_date(timestamp)
    return timestamp.strftime("%d.%m.%Y")
  end
  def message_datetime(message)
    return message.created_at.strftime("%d.%m.%Y - %H:%M")
  end
  def message_time(message)
    return message.created_at.strftime("%H:%M")
  end


  # orgin
  def fix_origin(message)
    if message.origin == "messages"
      return "comments"
    end

    return message.origin
  end


  # align
  def received_or_sent(user, message)
    id_andre = ["100001426361532", "Me"]
    id_linda = ["613348845421106", "Linda Voigt", "Babe"]


    if current_user.username == "andre"
      user_array = id_andre
    else
      user_array = id_linda
    end

    if user_array.include?(message.sender_contact)
      return "message-sent"
    else
      return "message-received"
    end
  end

  def message_back_path(message)

    if request.referer.split("/").last == "favorites"
      return favorites_path
    end

    if request.referer.split("/").last == "messages"
      return messages_path
    end

    if @message.page_url.present? && @message.page_url != nil
      return messages_path(page: message.page_url.gsub('page=', ''))
    end
  end
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sender_contact %><br>
    <%= f.text_field :sender_contact %>
  </div>
  <div class="field">
    <%= f.label :sender_name %><br>
    <%= f.text_field :sender_name %>
  </div>
  <div class="field">
    <%= f.label :receiver_contact %><br>
    <%= f.text_field :receiver_contact %>
  </div>
  <div class="field">
    <%= f.label :receiver_name %><br>
    <%= f.text_field :receiver_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :message_type %><br>
    <%= f.text_field :message_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/import_from_backup.erb
<div class="content-padded">
  <h4>Import Messages</h4>
  <%= form_tag import_messages_path, multipart: true do %>
    <p>
      <%= file_field_tag :file %>
    </p>
    <p>
      <%= submit_tag "Import", class: "btn btn-primary btn-block" %>
    </p>
  <% end %>
</div>

app/views/messages/index.html.erb
<% content_for(:title) do %>
  <h1 class="title">Messages</h1>
<% end %>


<% for month in @message_months do %>
  <div class="messages-listing-month">
    <%= get_date month.first %>
  </div>

  <ul class="messages-listing">
    <% month.last.each do |message| %>
      <li>
        <a class="messages-listing-message <%= received_or_sent(@current_user, message) %>" href="<%= url_for message %>" data-transition="slide-in">
          <div class="messages-listing-message-body">
            <%= message.body %>
          </div>
          <div class="messages-listing-message-time">
            <span><%= message_time(message) %></span>
            <span>·</span>
            <span><i class="fa fa-<%= fix_origin(message) %>"></i></span>
          </div>
        </a>
      </li>
    <% end %>
  </ul>

<% end %>

<%= paginate @messages %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<% content_for(:bar_buttons) do %>
  <a class="icon icon-left-nav pull-left" href="<%= message_back_path(@message) %>" data-transition="slide-out"></a>
<% end %>

<div class="content-padded">
  <h4>
    <%= @message.sender_name %>
  </h4>
  <p class="message-body">
    <%= @message.body %>
  </p>
  <p>
    <small>to <%= @message.receiver_name %> on <%= message_datetime(@message) %> via <span><i class="fa fa-<%= fix_origin(@message) %>"></i></span>
  </p>
  <hr>
  <%= render "favorites/message_show_form.html" %>
</div>