config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :favorites do
    member { post :vote }
  end

  get 'home/index', as: "home"

  get '/search' => "search#index", as: "search"

  resources :messages

  get "/backup" => 'messages#import_from_backup'
  post "/backup" => 'messages#import_from_backup_post', as: "import_messages"

  get "/facebook" => 'messages#import_from_facebook'

  root 'home#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  belongs_to :message
  belongs_to :user

  # defualt sort scope
  default_scope { order('created_at DESC') }

  scope :faved, lambda { where(['faved_at IS NOT NULL']) }

  before_save :trigger_fav

  def trigger_fav
    if self.faved_at == nil && self.unfaved_at == nil
      self.faved_at = DateTime.now
    elsif self.faved_at != nil && self.unfaved_at == nil
      self.unfaved_at = DateTime.now
      self.faved_at = nil
    elsif self.faved_at == nil && self.unfaved_at != nil
      self.unfaved_at = nil
      self.faved_at = DateTime.now
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = Favorite.all.faved
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite.message, notice: 'Favorite was successfully created.' }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite.message, notice: 'Favorite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    raise "Hi"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.require(:favorite).permit(:message_id, :user_id, :faved_at, :unfaved_at)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
  def get_fav_status(message)
    unless message.favorites.empty?
      fav = message.favorites.where(user_id: current_user.id).first

      if fav.faved_at != nil
        return "fav-status-faved"
      end
    end
  
    return ""
  end
end

app/views/favorites/_form.html.erb
<%= form_for(@favorite) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message_id %><br>
    <%= f.number_field :message_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :faved_at %><br>
    <%= f.datetime_select :faved_at %>
  </div>
  <div class="field">
    <%= f.label :unfaved_at %><br>
    <%= f.datetime_select :unfaved_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/_message_show_form.html.erb
<%= form_for(@favorite) do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :message_id, value: @message.id %>

  <div class="fav-status-wrapper">
    <div class="fav-status <%= get_fav_status(@message) %>">
      <i class="fa fa-star"></i>
    </div>
  </div>

  <%= f.submit "s", class: "submit-fav-input" %>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<ul class="table-view">
  <% @favorites.each do |favorite| %>
    <li class="table-view-cell media">
      <a class="navigate-right" href="<%= url_for favorite.message %>" data-transition="slide-in">
        <span class="media-object pull-left icon fa fa-star"></span>
        <div class="media-body">
          <%= favorite.user.firstname %>
          <p>
            <b><%= favorite.message.sender_name %></b> - <%= favorite.message.body %>
          </p>
        </div>
      </a>
    </li>
  <% end %>
</ul>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @favorite.message_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @favorite.user_id %>
</p>

<p>
  <strong>Faved at:</strong>
  <%= @favorite.faved_at %>
</p>

<p>
  <strong>Unfaved at:</strong>
  <%= @favorite.unfaved_at %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>