config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :favorites do
    member { post :vote }
  end

  get 'home/index', as: "home"

  get '/search' => "search#index", as: "search"

  resources :messages

  get "/backup" => 'messages#import_from_backup'
  post "/backup" => 'messages#import_from_backup_post', as: "import_messages"

  get "/facebook" => 'messages#import_from_facebook'

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>andre &amp; linda</title>
    <!-- Sets initial viewport load and disables zooming  -->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">

    <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">

    <!-- Include the compiled Ratchet CSS -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <!-- Include the compiled Ratchet JS -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>


    <!-- Make sure all your bars are the first things in your <body> -->
    <header class="bar bar-nav">
      <% if content_for(:bar_buttons) %>
        <%= yield :bar_buttons %>
      <% end %>
      <% if content_for(:title) %>
        <%= yield :title %>
      <% else %>
        <h1 class="title">andre &amp; linda</h1>
      <% end %>
    </header>

    <nav class="bar bar-tab">
      <%= navigation_link '<span class="icon fa fa-heart-o"></span><span class="tab-label">TFA</span>'.html_safe, home_path, :resource, class: "tab-item" %>
      <%= navigation_link '<span class="icon fa fa-envelope-o"></span><span class="tab-label">Messages</span>'.html_safe, messages_path, :resource, class: "tab-item" %>
      <%= navigation_link '<span class="icon fa fa-star-o"></span><span class="tab-label">Favorites</span>'.html_safe, favorites_path, :resource, class: "tab-item" %>
      <%#= navigation_link '<span class="icon icon-search"></span><span class="tab-label">Search</span>'.html_safe, search_path, :resource, class: "tab-item" %>
    </nav>

    <!-- Wrap all non-bar HTML in the .content div (this is actually what scrolls) -->
    <div id="content" class="content">
      <%= yield %>
    </div>
  </body>
</html>